import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'
 
const satoshi = localFont({ src: './Satoshi-Variable.woff2' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${satoshi.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
